# Utiliza una imagen base de PostgreSQL
FROM postgres:latest

# Variables de entorno para configurar la contraseña
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB parcial_db

# Expone el puerto de PostgreSQL
EXPOSE 5432
